version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  labels:
  - dependencies
  - python
  ignore:
  - dependency-name: fcm-django
    versions:
    - 0.3.8
  - dependency-name: django-extensions
    versions:
    - 3.1.1
    - 3.1.1.post1
    - 3.1.2
  - dependency-name: urllib3
    versions:
    - 1.26.3
  - dependency-name: django
    versions:
    - 3.1.6
  commit-message:
    prefix: Crowdbotics
